; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Thu Aug 13 2020 17:50:18 GMT+0200 (heure d’été d’Europe centrale)
M280 P0 S90 ; retract BLTouch

